### ISSUE TITLE
error when using flair collapse

### ISSUE THREAD

**Issue by wuhao08** [BrooksLabUCSC/flair#178] opened 2021-10-09 08:54 UTC
Thanks for this excellent tools!
I tried to use flair to perform isoform analysis for nanopore cDNA data. when using flair collapse , i only got flair.collapse.firstpass.bed and flair.collapse.firstpass.unfiltered.bed in the output floder. And Besides, i checked the output of flair, i only found:

Read data extracted
Single-exon genes grouped, collapsing
usage: script.py psl|bed genome.fa outfilename

and my code is: python /public/home/xudongfu/wuhao/software/pythonscript/flair.py collapse --keep_intermediate -g ${genomepath}/Mus_musculus.GRCm38.dna.primary_assembly.fa -q ${correctpath}/SRR11517473_all_corrected.bed -r ${filterdata}/SRR11517473_1_highQuality.fastq

so is there any error in my code? or i missed some important information?
thanks for your reply!

**Comment by RonjaSan** [comment] 2021-10-15 05:45
I'm having the same problem with collapse. Did you solve it?

**Comment by ctl43** [comment] 2021-10-19 04:06
Please see [https://github.com/BrooksLabUCSC/flair/issues/175](url) for the problem.

**Comment by wu1997-shu** [comment] 2021-12-10 04:10
I got the same problem, after cheaking the ref path found the path is error. Correct the path it's ok

**Comment by ctl43** [comment] 2021-12-10 05:52
If the problem is solved, it would be good to close this issue.

**Comment by Eduardo-vsouza** [comment] 2022-01-31 11:05
I got the same problem, and the paths do not seem to be the problem. Any updates on this error?

**Comment by Jeltje** [comment] 2022-07-22 20:43
Hi, we have vastly improved on Flair's error messaging and made a new release.
You can get it from github, or by running `pip install brookslab-flair`
There is also a docker image: `docker pull brookslab/flair:1.6.1`

If this release does not resolve your problem, please reopen this ticket. Thanks!

**Closed by Jeltje** 2022-07-22 20:43 UTC
