### ISSUE TITLE
predictProductivity.py error

### ISSUE THREAD

**Issue by ashokpatowary** [BrooksLabUCSC/flair#116] opened 2020-05-25 00:50 UTC
Hi @belgravia 

I was trying to use flair on Pacbio isoseq reads and encounter the following error while running  `predictProductivity.py` script. Initially, I though its because of naming so I changed the name by changing  '_' to '/'. But still I am facing the same error. Can you please have a look. Thanks

`Traceback (most recent call last):
  File "/u/home/a/ashokpat/Tools/flair/bin/predictProductivity.py", line 374, in <module>
    main()
  File "/u/home/a/ashokpat/Tools/flair/bin/predictProductivity.py", line 341, in main
    isoformObjs = predict(bed, starts, isoformObjs)
  File "/u/home/a/ashokpat/Tools/flair/bin/predictProductivity.py", line 256, in predict
    isoDict[read].strand = intersection[5]
KeyError: u'm54213/180915/054532/51970378/ccs_GL000241.1:34000'`

**Comment by mvheetve** [comment] 2020-05-26 09:14
Hi,

exactly same problem just now.

`mvheetve$ python biotools/flair/bin/predictProductivity.py -i Desktop/CMGG/ATM_MinION/RUN3/flair.collapse.isoforms.bed -f Desktop/GRCh37.p13_genomic.fna -g Desktop/GRCh37.p13_genomic.gtf --longestORF > MCF10AvsEBV_productivity.bed
Traceback (most recent call last):
  File "biotools/flair/bin/predictProductivity.py", line 374, in <module>
    main()
  File "biotools/flair/bin/predictProductivity.py", line 341, in main
    isoformObjs = predict(bed, starts, isoformObjs)
  File "biotools/flair/bin/predictProductivity.py", line 256, in predict
    isoDict[read].strand = intersection[5]
KeyError: '323fec1d-9aab-480d-9c49-d36fddf4af51_1_1_1_1_1_1_1_NC_000011.9:10208000'
`
Mattias

**Comment by belgravia** [comment] 2020-05-29 22:17
Hi,

Please update to the newest commit and try running predictProductivity again. I have now accounted for gene names formatted `NC_*`. Thanks for your patience.

@ashokpatowary I would rerun with the original file, not the one where you replaced underscores with slashes.

-Alison

**Comment by ashokpatowary** [comment] 2020-05-29 23:32
Hi @belgravia 

So, I updated  and decided to run my complete flair pipeline from the start. And now I am having an error in `collapse`. Bellow is the error. It ran perfectly in the earlier version.

```
Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
Renaming isoforms
Aligning reads to first-pass isoform reference
mv: cannot stat `/u/home/a/ashokpat/tmp/tmpUiNxUG.firstpass..sam': No such file or directory
Sam file issue and/or if --stringent was specified, so must a valid isoforms file
Failed at counting step for isoform read support
```

**Comment by belgravia** [comment] 2020-05-30 02:14
Hi,

Thanks for pointing that out. I made a bunch of changes under the hood to flair.py and committed too much too early probably!

Well I have fixed the issue, and hopefully that means you didn't have problems running the align/correct module? Either way, please try running collapse again after updating. 
-Alison

**Comment by ashokpatowary** [comment] 2020-05-30 02:45
Hi @belgravia 
I cannot comment on align module as I dont re-run it every time. But yes, there was no error with correct module. Though with the update collapse module is working now, I am still having error with productivity script. Here is the error. Thanks

```
***** WARNING: File /tmp/pybedtools.Hc2Rta.tmp has inconsistent naming convention for record:
GL000241.1      34529   36896   m54213_180915_054532/51970378/ccs_GL000241.1:34000      60      -

***** WARNING: File /tmp/pybedtools.Hc2Rta.tmp has inconsistent naming convention for record:
GL000241.1      34529   36896   m54213_180915_054532/51970378/ccs_GL000241.1:34000      60      -

Traceback (most recent call last):
  File "/u/home/a/ashokpat/Tools/flair/bin/predictProductivity.py", line 371, in <module>
    main()
  File "/u/home/a/ashokpat/Tools/flair/bin/predictProductivity.py", line 338, in main
    isoformObjs = predict(bed, starts, isoformObjs)
  File "/u/home/a/ashokpat/Tools/flair/bin/predictProductivity.py", line 253, in predict
    isoDict[read].strand = intersection[5]
KeyError: u'm54213_180915_054532/51970378/ccs_GL000241.1:34000'
```

**Comment by ozgegizlenci** [comment] 2020-06-08 11:57
Hello,

I also receive a similar error with predictproductivity.
It was a different error before the update. 

Here is my commend:

`python ../bin/predictProductivity.py -i /bi/home/gizlenco/FLAIR/ONT-14-v15-analysis/ONT-14.merged.isoforms.psl -f /bi/home/gizlenco/Reference/GRCm38.primary_assembly.genome.fa -g /bi/home/gizlenco/ONT-14-complete/flair/gencode.vM24.annotation.gtf --longestORF`

this is reported error below:

`Traceback (most recent call last):
  File "../bin/predictProductivity.py", line 371, in <module>
    main()
  File "../bin/predictProductivity.py", line 338, in main
    isoformObjs = predict(bed, starts, isoformObjs)
  File "../bin/predictProductivity.py", line 253, in predict
    isoDict[read].strand = intersection[5]
KeyError: '7ade25dc-384e-4395-b89d-a0507082ceb2_chr11:3104000'`

Thank you!

**Comment by belgravia** [comment] 2020-06-15 22:46
As always thanks for patience. It's hard for me to debug these with this information since it looks like the commands are fine. It looks like for some reason, some isoforms aren't in the fasta file produced by pybedtools and so the isoforms aren't being added to a dictionary.

It would be easiest for me if either one of you (or both) sent me snippets of the file you are working with. It could just be the entry for the problematic isoform that causes the error. I'll try running predictProductivity to see if I can try to replicate your errors.

-Alison

**Comment by ashokpatowary** [comment] 2020-06-19 03:32
@belgravia 

Can you share your email id? I will be happy to share the files with you.

Thanks

**Comment by belgravia** [comment] 2020-06-20 00:03
Please share it with alison.tang@ucsc.edu, thanks!
-Alison

**Comment by belgravia** [comment] 2020-06-29 22:41
Did you ever send me your file snippets? I don't think I saw anything in my inbox.
-Alison

**Comment by ashokpatowary** [comment] 2020-06-29 22:46
@belgravia I will say it co-incident; but you should receive it by now.

**Comment by ashokpatowary** [comment] 2020-07-06 18:06
@belgravia did you receive the data??

**Comment by belgravia** [comment] 2020-07-08 01:40
Hi @ashokpatowary,

I was able to run predictProductivity on your data to completion in my flair conda environment. I'm not sure if I used the right genome or annotation (I used GRCh37.p13 and gencode.v19) but I got many productive isoforms, no-start isoforms, and some PTC isoforms and some isoforms categorized as no-stop. Which is to say that it ran, was able to use the starts from the gtf, and was able to use the sequence from the genome to predict stops. For now, I am ruling out that the issue is with the data are it's probablyy something to do with your environment I'm guessing.

Have I already asked what version of bedtools are you using? I don't want to sound like a broken record, but some versions of bedtools have output that is formatted differently than other versions of bedtools. I'm using v2.25.0 of bedtools. 

-Alison

**Comment by ashokpatowary** [comment] 2020-07-17 05:29
@belgravia can you try with Gencode v33 once. I think it might be a gencode issue because I faced a different issue with some other tool; but latter it appears it because of gencode v33.

**Comment by belgravia** [comment] 2020-07-30 00:20
I tried running the command on your data again with same genome I used last time (GRCh37.p13) but using gencode v33 as you suggested and it seemed to run successfully.

I'm wondering if it's a genome sequence file compatibility issue. I'm using gencode v33 annotation downloaded from gencode (https://www.gencodegenes.org/human/releases.html). On the website, it says that the genome assembly version for v33 is GRCh38. So I'm a little confused because your example command that you sent to me in email used a file called `GRCH37.primary_assembly.genome.fa`.

So then I ran my command on your data using gencode v33 but with GRCh38 and then I get a lot of warnings that look like: `WARNING. chromosome (GL000241.1) was not found in the FASTA file. Skipping.` and then I get the `isoDict[read].strand = intersection[5]` key error that you showed me. That error will come up if the chromosome names in your isoforms.bed file don't match the chromosome names in your genome sequence file. The GRCh37 fasta had a chromosome named GL000241.1  in it but GRCh38 didn't. So maybe double check the genome assembly versions is the right one and in particular, check that you don't have chromosome names present in your isoforms.bed file that aren't present in your genome fasta. 

-Alison

**Closed** 2020-09-12 00:38 UTC
