### ISSUE TITLE
the -i  isoform.fa of flair_quantify issue

### ISSUE THREAD

**Issue by q1134269149** [BrooksLabUCSC/flair#55] opened 2019-09-22 14:20 UTC
Hi,
I used flair to quantify FLAIR isoform usage. I  don't know how to set the parameter of -i (isoform.fasta). I have two groups (a total of six samples ) and each group contains three repeats.  I ran  flair_collapse for each of the six samples, and **get six isoform.fasta files**. When I run flair_quantify, the -r (reads_manifest.tsv) as following table, but **how do I set the -i parameter of flair_quantify module**? 
"""
reads_manifest.tsv:
A1  wt      batch1  ./A1.qf.fastq
A2  wt      batch1  ./A2.qf.fastq
A3  wt      batch1  ./A3.qf.fastq
B1 mut        batch1  ./B1.qf.fastq
B2 mut        batch1  ./B2.qf.fastq
B3 mut        batch1  ./B3.qf.fastq
"""
"""
The six isoform.fasta from flair_collapse module as following:
A1_flair.collapse.isoforms.fa
A2_flair.collapse.isoforms.fa
A3_flair.collapse.isoforms.fa
B1_flair.collapse.isoforms.fa
B2_flair.collapse.isoforms.fa
B3_flair.collapse.isoforms.fa
"""
Could you give me some advice? Thanks.

**Comment by belgravia** [comment] 2019-09-24 17:31
We recommend that you concatenate the corrected reads for all 6 of your files into a single file, and then run FLAIR-collapse on that single file. For the FLAIR-collapse `-r` argument, you can provide a comma-separated list of your fastqs (like `A1.qf.fastq,A2.qf.fastq,A3.qf.fastq...`) or you could combine them into a single file. 

The resulting isoform.fa file will contain the isoforms that contain sufficient support between all of your 6 samples. You can supply that single .fa file to the quantify module to then quantify the expression of the isoforms for each of your samples.

Hope that helps.
-Alison

**Comment by q1134269149** [comment] 2019-09-25 12:56
OK,Thanks. And **when I ran the diffExp, I got the following errors:**
"""
running DESEQ2 dge
Traceback (most recent call last):
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/runDE.py", line 218, in <module>
    main()
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/runDE.py", line 110, in main
    df = pandas2ri.py2ri(quantDF)
AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'
running DESEQ2 die
Traceback (most recent call last):
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/runDE.py", line 218, in <module>
    main()
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/runDE.py", line 110, in main
    df = pandas2ri.py2ri(quantDF)
AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'
running DRIMSEQ diu
Traceback (most recent call last):
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/runDU.py", line 193, in <module>
    main()
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/runDU.py", line 116, in main
    df       = pandas2ri.py2ri(quantDF)
AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'
"""
**I cloned your conda environment from github, and before ran diffExp, I installed the rpy2 3.1.0.**
**And I tried to import packages as following, all is ok.**
"""
import os, sys
import pandas as pd
import numpy as np
from rpy2 import robjects
from rpy2.robjects import r,pandas2ri, Formula
from rpy2.robjects.lib import grid
pandas2ri.activate()
R = robjects.r
import warnings
from rpy2.rinterface import RRuntimeWarning
"""
**But run the code of "pandas2ri.py2ri()", returning the error :**
"""
AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'
"""
Can you give me some advice? Thanks.

**Comment by q1134269149** [comment] 2019-09-25 13:06
"""
(flair_env) [shihan@node6 cf_diffExp.out]$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, sys
>>> import pandas as pd
>>> import numpy as np
>>> from rpy2 import robjects
>>> from rpy2.robjects import r,pandas2ri, Formula
>>> from rpy2.robjects.lib import grid
>>> pandas2ri.activate()
>>> R = robjects.r
>>> import warnings
>>> from rpy2.rinterface import RRuntimeWarning
>>> warnings.filterwarnings("ignore", category=RRuntimeWarning)
>>> import argparse
>>> from rpy2.robjects.packages import importr
>>>  import rpy2.robjects.lib.ggplot2 as ggplot2
  File "<stdin>", line 1
    import rpy2.robjects.lib.ggplot2 as ggplot2
    ^
IndentationError: unexpected indent
>>> import rpy2.robjects.lib.ggplot2 as ggplot2
>>> pandas2ri.py2ri()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'
>>>

"""

**Comment by q1134269149** [comment] 2019-09-25 13:20
Is it necessary to change the "pandas2ri.py2ri" to "pandas2ri.py2rpy"?

**Comment by csoulette** [comment] 2019-09-25 14:24
Hi,

The issue is due to the rpy2 version. In your condo environment, you can `pip install rpy2==2.9.5`, and all should be fixed. Thanks for catching this. 

-CMS

**Comment by q1134269149** [comment] 2019-09-25 14:58
> Hi,
> 
> The issue is due to the rpy2 version. In your conda environment, you can `pip install rpy2==2.9.5`, and all should be fixed. Thanks for catching this.
> 
> -CMS

Hi, 
Thank you for your advice. Becaues I have installed rpy2-3.1.0, so I changed all "pandas2ri.py2ri" to "pandas2ri.py2rpy" in the runDE.py and runDU.py file. It worked. 
Thanks.

**Comment by q1134269149** [comment] 2019-09-25 15:01
> We recommend that you concatenate the corrected reads for all 6 of your files into a single file, and then run FLAIR-collapse on that single file. For the FLAIR-collapse `-r` argument, you can provide a comma-separated list of your fastqs (like `A1.qf.fastq,A2.qf.fastq,A3.qf.fastq...`) or you could combine them into a single file.
> 
> The resulting isoform.fa file will contain the isoforms that contain sufficient support between all of your 6 samples. You can supply that single .fa file to the quantify module to then quantify the expression of the isoforms for each of your samples.
> 
> Hope that helps.
> -Alison

Hi,
I suggest that you can list and update the versions of all dependency packages installed in your conda environment, which will help users install the appropriate versions. Thanks very much!

**Comment by q1134269149** [comment] 2019-09-25 15:04
> Hi,
> 
> The issue is due to the rpy2 version. In your conda environment, you can `pip install rpy2==2.9.5`, and all should be fixed. Thanks for catching this.
> 
> -CMS

Hi,
I suggest that you can list and update the versions of all dependency packages installed in your conda environment, which will help users install the appropriate versions. Thanks very much!

**Closed** 2019-09-28 01:49 UTC
