### ISSUE TITLE
diffExp-rpy2.rinterface.RRuntimeError

### ISSUE THREAD

**Issue by ozgegizlenci** [BrooksLabUCSC/flair#100] opened 2020-02-26 16:32 UTC
Hello,

  I am using flair to analyse differential isoforms in nanopore data.  I followed the steps and succesfully finished the analysis until the quantification step. However, when it comes to the diffExp analysis with flair, it unfortunately fails due to the module errors or packages required in the environment. I created the flair environment using conda and run the diffexp using the command below: 
 
`ssub -c32 --mem=64G python3 flair.py diffExp -q counts_matrix.tsv --out_dir flair-diff-exp -t 32`
 
The first error I used to get was:
 
`AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'`
 
I realised that my rpy2 was 3.1.0 so I changed it to 2.9.5.
 
It seems like it did not help to smoothly run the code so I have a different type of error:

[dge_stderr.ColdataError.txt](https://github.com/BrooksLabUCSC/flair/files/4256896/dge_stderr.ColdataError.txt)

running DESEQ2 dge
Traceback (most recent call last):
  File "/bi/home/gizlenco/ONT-14-complete/flair/bin/runDE.py", line 218, in <module>
    main()
  File "/bi/home/gizlenco/ONT-14-complete/flair/bin/runDE.py", line 137, in main
    R('dds <- DESeqDataSetFromMatrix(countData = df, colData = sampleTable, design = design)')
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in .validate_names(colnames, ans_colnames, "assay colnames()", "colData rownames()") : 
  assay colnames() must be NULL or identical to colData rownames()

I googled the issue; however, I was not able to find what the reason might be specifically for flair. I will appreciate if you could help me to understand it.
 
Here are my formula matrix and read manifest files if it helps to resolve the issue (note: I attached them as txt file).

[formula_matrix.txt](https://github.com/BrooksLabUCSC/flair/files/4256924/formula_matrix.txt)

[reads_manifest.txt](https://github.com/BrooksLabUCSC/flair/files/4256925/reads_manifest.txt)

 Thank you very much in advance. 
Ozge

**Comment by belgravia** [comment] 2020-03-13 22:14
Glad you were able to figure out the rpy issue. We currently have it specified as rpy 2.9* in the conda environment so hopefully other users won't run into this issue. If you can, you could try running the diffExp in the flair conda environment (misc/flair_conda_env.yaml) and see if that also helps with the DESeq2 problem. 

Can you send me the first couple lines of your counts matrix? I am also wondering if it might be something to do with how the isoform names are formatted. 

Thanks for your patience.

**Comment by yoon5812** [comment] 2020-04-01 15:13
Hi  Alison,

I have the same error. I installed anaconda3, configured the flair_env using your misc/flair_conda_env.yaml, and activated it.

Here I attach formula matrix, read manifest, and count matrix (first 100 lines) files. 

[formula_matrix.txt](https://github.com/BrooksLabUCSC/flair/files/4416088/formula_matrix.txt)
[reads_manifest.txt](https://github.com/BrooksLabUCSC/flair/files/4416091/reads_manifest.txt)
[counts_matrix.txt](https://github.com/BrooksLabUCSC/flair/files/4416093/counts_matrix.txt)

Please help me. 
Thank you

Yoon

**Comment by yoon5812** [comment] 2020-04-02 05:31
Hello Ozge and Alison,

I found the reason. 

It's the hyphen "-" that made these errors. R does not allow column names containing a hyphen or starting with a number. Because I am not familiar with R, I put a hyphen in column names.

Solution: First three columns of the "reads_manifest.tsv" should not contain a hyphen nor start with a number. Use alphabets and numbers only.

Yoon

**Comment by chalybes** [comment] 2020-04-23 09:45
I have a similar diffExp problem, also a rpy2.rinterface.RRuntimeError but different context: 

When I run diffExp, at runDE this happens: 
```
rpy2.rinterface.RRuntimeError: Error in results(dds, name = name) :
  the argument 'name' should be a character vector of length 1
```
At runDU: 

```
rpy2.rinterface.RRuntimeError: Error in validObject(.Object) :
  invalid class “dmDSprecision” object: invalid object for slot "genewise_precision" in class "dmDSprecision": got class "logical", should be or extend class "numeric"
```

I made sure that my rpy2 version is 2.9, so I don't know what is causing this issue. I also don't have hyphens or special characters in my column names. Any help would be appreciated (should I make a separate thread from this?)

**Comment by ozgegizlenci** [comment] 2020-06-08 11:23
Hello, 

Thank you for the previous responses.
I will revive the post again with the consistent error I was not able to run diffExp in completion.

I realised I am missing the outputs as far as I understood it from the previous posts. My output only includes:

dge_stderr.txt
filtered_gene_counts_ds2.tsv
filtered_iso_counts_drim.tsv
filtered_iso_counts_ds2.tsv
formula_matrix.tsv

I tried to run the diffExp function using both flair v1.4 and flair v1.5 in conda environment as you've suggested. Here is the error I receive constantly:

`running DESEQ2 dge
Traceback (most recent call last):
  File "/bi/home/gizlenco/FLAIR/bin/runDE.py", line 216, in <module>
    main()
  File "/bi/home/gizlenco/FLAIR/bin/runDE.py", line 137, in main
    R('name <- grep("condition", resultsNames(dds), value=TRUE)')
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 353, in __call__
    return conversion.ri2py(res)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py", line 139, in ri2py_vector
    res = numpy2ri.ri2py(obj)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/rpy2/robjects/numpy2ri.py", line 159, in ri2py_sexp
    res = numpy.asarray(obj)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: Buffer for this type not yet supported.
running DESEQ2 die
Traceback (most recent call last):
  File "/bi/home/gizlenco/FLAIR/bin/runDE.py", line 216, in <module>
    main()
  File "/bi/home/gizlenco/FLAIR/bin/runDE.py", line 137, in main
    R('name <- grep("condition", resultsNames(dds), value=TRUE)')
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 353, in __call__
    return conversion.ri2py(res)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py", line 139, in ri2py_vector
    res = numpy2ri.ri2py(obj)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/rpy2/robjects/numpy2ri.py", line 159, in ri2py_sexp
    res = numpy.asarray(obj)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: Buffer for this type not yet supported.
running DRIMSEQ diu
Traceback (most recent call last):
  File "/bi/home/gizlenco/FLAIR/bin/runDU.py", line 194, in <module>
    main()
  File "/bi/home/gizlenco/FLAIR/bin/runDU.py", line 147, in main
    R('contrast <- grep("condition",colnames(design_full),value=TRUE)')
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 353, in __call__
    return conversion.ri2py(res)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py", line 139, in ri2py_vector
    res = numpy2ri.ri2py(obj)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/rpy2/robjects/numpy2ri.py", line 159, in ri2py_sexp
    res = numpy.asarray(obj)
  File "/bi/home/gizlenco/anaconda3/envs/flair/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: Buffer for this type not yet supported.`

I will be so happy if you could help me to understand what the problem might be stemming from.
Here I attached a couple of lines from my counts_matrix too:
[counts_matrix_edited.txt](https://github.com/BrooksLabUCSC/flair/files/4745612/counts_matrix_edited.txt)

Thank you so much in advance.
Ozge

**Comment by belgravia** [comment] 2020-06-18 19:29
Ozge - Thanks for attaching some of your counts matrix. It looks fine to me. Thanks for also trying it with both versions of flair in the conda environment. 
From googling the ValueError, it appears that this may be an issue with certain numpy versions that are incompatible with rpy2. I was able to reproduce the ValueError when my numpy version was 1.18.5. When I changed to version 1.9 (`conda install numpy=1.9`) which is the version specified in the conda environment .yaml, I was able to get the diffExp module working. I also had to make sure that the numpy version actually got switched to 1.9 using `export PYTHONNOUSERSITE=True`. There should be DGE, DIE, and DIU results outputs. Let me know if this solves your issue. An alternative solution may be to upgrade rpy2 to 3.1*. 

@chalybes - it may be helpful for me to see your counts matrix. Your errors seem to be related to problems with input.

**Comment by mvheetve** [comment] 2020-10-05 06:55
Hi,

would it be possible to patch flair with the latest ryp2 version? We are trying to run flair in combination with other software and changing to rpy2 2.9 creates problems for other dependencies. 

Kind regards
Mattias

**Comment by Jeltje** [comment] 2022-09-06 18:44
I believe Flair now works with rpy 3.5

We have also created a docker container:

`docker pull brookslab/flair:latest`

You can then run flair commands like so
``docker run -v `pwd`:/mydata -w /mydata brookslab/flair:latest flair diffExp (...)``

(note that you no longer need the .py extension after flair)

If this solves your problem to your satisfaction, please close this ticket.

We are working to make Flair conda installable but this might take a while.

**Comment by Jeltje** [comment] 2022-09-28 20:26
Flair can now be conda installed:

`conda install -c conda-forge -c bioconda flair`

**Closed by Jeltje** 2022-09-28 20:26 UTC
